* 简介
反馈、交流，请使用如下方式：
添加微信，回复: ewechat  , 拉入微信交流群
添加QQ 验证消息: ewechat , 拉入QQ群

* 支持微信
做成表格 使用百度网盘
版本 下载地址 md5
* Bugs
** 反馈bug的流程
** 使用者信息登记
做成表格
插件分为长期支持版本（lts）、 稳定版本（stable）、测试版本（dev）
微信版本分为长期版本、最新版本
最新版本为微信官方发布的版本，下载地址
插件版本和微信版本，会变动，不一定能即使更新对应每个人的实际情况。长期支持版本的人单独拉个测试群
** 微信长期支持版本选择
可以开启群住确认
支持小程序
** 微信版本
*** 官方版本和pay版本
第三方应用市场太多，存在二次打包，无法顾及

为什么微信经常通过应用内升级更新，而不首先更新Google Play市场？ - 知乎
https://www.zhihu.com/question/21964000

pay在国内使用少
官方的用户数多，可以自动更新
官方的可以用热更新，自动更新，无需用户干预。pay需要审核，发布时间慢
官方的会出内测版本，可以在内测版本上适配，正式版本的发布了，可以为正式发布版本适配争取时间

*** 历史版本
微信，是一个生活方式
http://weixin.qq.com/cgi-bin/readtemplate?t=weixin_faq_list

这里可以查看版本的更新说明，但是下载的都是最新版本
 
*** android  
**** 6510
可以设置某条朋友圈的互动不再通知
***** 朋友圈互动不再通知
长按朋友圈的消息，会弹出 不再通知/删除 菜单
**** 658
可在微信实验室体验正在探索的功能。
聊天中查找聊天内容时，可以查找文件、图片、链接。
6581

群主可在群成员信息页中，了解对方是如何加入群聊的。
6582

选择图片时，可便捷地调整并预览已选择的内容。
6583
**** 657
解决了一些已知问题
**** 656
解决了一些已知问题
**** 654
可以通过二维码给身边的人发红包
6541

选择照片时，可进行简单的编辑
6542

看不完的文章，可以先置顶到聊天中
**** 653
可以在朋友圈分享相册中的视频
6531

新的语音输入，更快更准
6532

**** 6332
解决了一些已知问题
**** 6331
群聊中可以按群成员和日期查找聊天内容
**** 6330
解决了一些已知问题
**** 6328
群主可启用需群主确认才可邀请朋友进群功能。

群聊里也可以收钱了。

*** ios
** 格式
群昵称 手机型号 ROM xposed版本 插件版本 微信版本

** log提交工具
* 快速入门
* 演示
操作视频，上传
* 用户手册
** 准备
*** 手机
**** 小米
***** 小米需要解锁分区和bl锁
小米有专门的框架
***** 小米5
***** 小米2s
***** 小米note
**** 红米
***** 红米pro2
**** 华为
**** 三星
***** s6
***** s7 edge
**** 魅族
**** 一加
**** oppo 
**** vivo
***** y55l
**** 华为
刷康大的包

**** 索尼 
*** 解锁
*** Recovery
*** ROM 
**** 小米
***** 小米开发版

*** Root
*** xposed 
**** 安装xp流程
手机解锁
刷第三方rec
刷rom
root手机
安装框架zip
安装框架apk

**** 版本
5.0以下的安卓不需要刷zip底包，直接安装apk就可以
**** 更新说明
**** 支持安卓版本
***** 7.0
Xposed for Lineage OS Android 7.1.1 | OnePlus One
https://forum.xda-developers.com/oneplus-one/help/xposed-lineage-os-android-7-1-1-t3561309

How To Install Xposed On Android Nougat 7/7.1 - Working Proof!
http://www.dexteroid.com/how-to/install-xposed-framework-on-android-nougat-7/

*** wechat
**** 版本
6.58 比较卡
6.5.7好一些 
**** 减少封号
***** 腾讯公益捐款，减少封号
*** ewechat 
** 防撤回
*** 防撤回原理 
*** 防撤回成功提示
*** 防撤回失败提示
单独列出来

有的是微信自带的撤回功能

有的是用户删除了，但是在本地的数据库上
* 开发者手册
ewechat
node学习资料
gradle
资源混淆
热补丁tinker
注释
代码风格
*** ref
Android动态破解微信本地数据库(EnMicroMsg.db) - njweiyukun的博客 - CSDN博客
http://m.blog.csdn.net/njweiyukun/article/details/54024442

**** fkzhang
**** veryyoung
**** muoli
* 资料
** XposedHelper
xposed开发辅助工具

